#!/usr/bin/env ruby

require "rubygems"
require "commander"
require "commander/import"
require 'bootstrap'

Commander.configure do
  program :name, "rumin"
  program :version, "2.0"
  program :description, "text editor"

  default_command :run

  command :run do |c|
    c.syntax = "rumin"
    c.description = "Edit a new file."

    # TODO 起動時にファイル名などの引数を取れるようにする
    # c.action do |args, options|
    # end
  end
end

# CommanderのModular style
Bootstrap.new.run
