#!/usr/bin/env ruby

require "rubygems"
require "commander"
require "commander/import"
require 'bootstrap'

Commander.configure do
  program :name, "rumin"
  program :version, "2.0alpha"
  program :description, "text editor"

  command :new do |c|
    c.syntax = "rumin"
    c.description = "Edit a new file."
    c.action do |args, options|
      rumin = Rumin.new
    end
  end
end
